### PR TITLE
Use type level lists for pagination on multiple fields

### PR DESCRIPTION
**Pull request by jbransen**
@KtorZ Here is my take on the type level lists. Inspired by #4 for sure, but I did start with master again because I felt that would keep it as close to the previous version as possible.

### CODE REVIEW

**Comment by KtorZ** [comment]
Hmmmm.... I was very confused for a second because that's, a couple of details aside, what was my very first approach (before switching from symbols to types) but GHC wasn't happy about the ambiguity of the `Range` constructor... There's one important difference in your implementation:

```
    , rangeField  :: Proxy field
```

And... now that I see it, it is indeed obvious :| ... Without that, `field` doesn't appear in the `Range` constructor and therefore, it's not possible to reify the `RangeType res field` to a unique type. That's great :D ! 
Thanks! 
I'll join the two implementation and review the examples a bit and I believe we'll be all set.

**Comment by jbransen** [comment]
I just realize there is something missing though: there is no connection between `field` and `fields`. Nothing prohibits you to create a range value for a field that is not in the list of fields... So in the definition of `Range` there should be a constraint that `field` is in `fields`.

**Comment by KtorZ** [comment]
Yes, we can use `Elem` from Servant.API.TypeLevel for that I guess. I'll look into it.

**Comment by KtorZ** [comment]
https://hackage.haskell.org/package/servant-0.13/docs/Servant-API-TypeLevel.html#t:Elem

**Comment by KtorZ** [comment]
Well, I've hacked a bit on it this weekend without much success. I first did re-align the branch with the work done on #4 (cleaning up and removing a couple of stuff I think shouldn't be in the library). 

Then, starting to introduce a constraint on the `field` from the `Range` constructor makes `liftRange` much harder to write. 

```hs
import Servant.API.TypeLevel(Elem)

data Range (fields :: [Symbol]) typ =
  forall field. 
  ( Elem field fields
  , KnownSymbol field
  , HasPagination typ field
  , IsRangeType (RangeType typ field)
  ) => Range
  -- ...
```

I'd thought that pattern-matchin on the `Range{..}` in `liftRange` would be enough to convince GHC, but I am missing something. I still have a couple of idea I want to try though.

**Comment by KtorZ** [comment]
Got it! Thanks to a colleague who pointed me to a nice resource. The idea is to define `Ranges` as a recursive structure using GADTs:

```hs
-- An actual Range parsed from a `Range` header. A Range
data Ranges :: [Symbol] -> * -> * where
  Lift   :: Ranges fields typ -> Ranges (y ': fields) typ
  Ranges ::
   ( KnownSymbol field
   , HasPagination typ field
   , IsRangeType (RangeType typ field)
   ) => Range field (RangeType typ field) -> Ranges (field ': fields) typ

data Range (field :: Symbol) (a :: *) = Range
  { rangeValue  :: Maybe a     -- ^ The value of that field, beginning of the range
  , rangeLimit  :: Int         -- ^ Maximum number of resources to return
  , rangeOffset :: Int         -- ^ Offset, number of resources to skip after the starting value
  , rangeOrder  :: RangeOrder  -- ^ The order of sorting (ascending or descending)
  , rangeField  :: Proxy field -- ^ Actual field this Range actually refers to
  }
```

This makes the `Range` belonging to the `Ranges` by construction. We can then derive a couple of type-class to extract or lift the inner `Range` and it works quite well :) 

Let me know what you think of that @jbransen

**Comment by jbransen** [comment]
Ah yes of course, this is the right solution. Nice one!

**Pull request merged**
