### PR TITLE
Allow servant-0.17

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
ping

**Comment by jbransen** [comment]
CI fails for your branch, so maybe you could fix that?

**Comment by phadej** [comment]
Sorry, won't do. I'm quite sure the master is broken too.

**Comment by KtorZ** [comment]
I can have a look a bit later this week. I've got another package to update first.

**Comment by phadej** [comment]
ping

**Comment by KtorZ** [comment]
_might fail because of time needed to rebuild the uncached new LTS_

**Comment by KtorZ** [comment]
@phadej I pushed on your branch... because I could. Cheers.

**Comment by KtorZ** [comment]
(Thanks for the bump & notice)

**Pull request merged**
